; Valores actuales que usa el theme.xml
aspectRatio = 16-9
colorScheme = dark

; ===========================
;  Opciones visibles en ES-X
; ===========================

[aspectRatio]
label      = Relación de aspecto
type       = select
values     = 16-9|16:9,16-10|16:10
default    = 16-9

[colorScheme]
label      = Esquema de color
type       = select
values     = dark|Oscuro,light|Claro
default    = dark

